name: vae
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4=pyh9f0ad1d_0
  - appnope=0.1.2=py39h6e9494a_1
  - argon2-cffi=20.1.0=py39h89e85a6_2
  - astroid=2.6.2=py39hecd8cb5_0
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyh44b312d_0
  - blosc=1.21.0=he49afe7_0
  - bokeh=2.3.3=py39h6e9494a_0
  - bottleneck=1.3.2=py39he3068b8_1
  - brotli=1.0.9=h0d85af4_5
  - brotli-bin=1.0.9=h0d85af4_5
  - brotlipy=0.7.0=py39h89e85a6_1001
  - brunsli=0.1=h046ec9c_0
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.17.1=h0d85af4_1
  - ca-certificates=2021.5.30=h033912b_0
  - certifi=2021.5.30=py39h6e9494a_0
  - cffi=1.14.6=py39hb71fe58_0
  - cfitsio=3.470=h01dc385_7
  - chardet=4.0.0=py39h6e9494a_1
  - charls=2.2.0=h046ec9c_0
  - click=8.0.1=py39h6e9494a_0
  - cloudpickle=1.6.0=py_0
  - colorcet=2.0.6=pyhd8ed1ab_0
  - cryptography=3.4.7=py39ha2c9959_0
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py39h89e85a6_3
  - dask=2021.7.0=pyhd8ed1ab_0
  - dask-core=2021.7.0=pyhd8ed1ab_0
  - datashader=0.13.0=pyh6c4a22f_0
  - datashape=0.5.4=py_1
  - debugpy=1.3.0=py39h9fcab8e_0
  - decorator=5.0.9=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distributed=2021.7.0=py39h6e9494a_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - freetype=2.10.4=ha233b18_0
  - fsspec=2021.7.0=pyhd8ed1ab_0
  - giflib=5.1.7=h01d97ff_1
  - heapdict=1.0.1=py_0
  - holoviews=1.14.4=pyhd8ed1ab_0
  - idna=2.10=pyh9f0ad1d_0
  - imagecodecs=2021.6.8=py39h2ea9c00_0
  - imageio=2.9.0=py_0
  - importlib-metadata=4.6.1=py39h6e9494a_0
  - intel-openmp=2021.2.0=hecd8cb5_564
  - ipykernel=6.0.1=py39h71a6800_0
  - ipython=7.25.0=py39h71a6800_1
  - ipython_genutils=0.2.0=py_1
  - isort=5.6.4=py_0
  - jedi=0.18.0=py39h6e9494a_2
  - jinja2=3.0.1=pyhd8ed1ab_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9b=he5867d9_2
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py39h6e9494a_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jxrlib=1.1=h35c211d_2
  - kiwisolver=1.3.1=py39hf018cea_1
  - krb5=1.19.1=hcfbf3a7_0
  - lazy-object-proxy=1.6.0=py39h9ed2024_0
  - lcms2=2.12=hf1fd2bf_0
  - lerc=2.2.1=h046ec9c_0
  - libaec=1.0.5=he49afe7_0
  - libblas=3.9.0=9_mkl
  - libbrotlicommon=1.0.9=h0d85af4_5
  - libbrotlidec=1.0.9=h0d85af4_5
  - libbrotlienc=1.0.9=h0d85af4_5
  - libcblas=3.9.0=9_mkl
  - libcurl=7.77.0=hf45b732_0
  - libcxx=12.0.1=habf9029_0
  - libdeflate=1.7=h35c211d_5
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=5.0.0=9_3_0_h6c81a4c_22
  - libgfortran5=9.3.0=h6c81a4c_22
  - liblapack=3.9.0=9_mkl
  - libllvm10=10.0.1=h009f743_3
  - libnghttp2=1.43.0=h07e645a_0
  - libpng=1.6.37=ha441bb4_0
  - libprotobuf=3.17.2=hcf210ce_1
  - libsodium=1.0.18=hbcb3906_1
  - libssh2=1.9.0=h52ee1ee_6
  - libtiff=4.1.0=hcb84e12_1
  - libuv=1.40.0=haf1e3a3_0
  - libwebp=1.0.1=hd73b212_0
  - libzopfli=1.0.3=h046ec9c_0
  - llvm-openmp=12.0.1=hda6cdc1_0
  - llvmlite=0.36.0=py39h798a4f4_0
  - locket=0.2.0=py_2
  - lz4-c=1.9.3=h23ab428_0
  - markdown=3.3.4=pyhd8ed1ab_0
  - markupsafe=2.0.1=py39h89e85a6_0
  - matplotlib=3.4.2=py39h6e9494a_0
  - matplotlib-base=3.4.2=py39hb07454d_0
  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
  - mccabe=0.6.1=py39hecd8cb5_1
  - mistune=0.8.4=py39h89e85a6_1004
  - mkl=2021.2.0=hecd8cb5_269
  - mkl-service=2.4.0=py39h9ed2024_0
  - mkl_fft=1.3.0=py39h4a7008c_2
  - mkl_random=1.2.1=py39hb2f4e1b_2
  - mord=0.6=py_0
  - msgpack-python=1.0.2=py39hf018cea_1
  - multipledispatch=0.6.0=py_0
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.1.0=py39h6e9494a_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h0a44026_1
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - networkx=2.3=py_0
  - ninja=1.10.2=hf7b0b51_1
  - notebook=6.4.0=pyha770c72_0
  - numba=0.53.1=py39h32e38f5_1
  - numexpr=2.7.3=py39h5873af2_1
  - numpy=1.20.2=py39h4b4dc7a_0
  - numpy-base=1.20.2=py39he0bd621_0
  - olefile=0.46=py_0
  - openjpeg=2.3.0=hb95cd4c_1
  - openssl=1.1.1k=h0d85af4_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.2.5=py39h23ab428_0
  - pandoc=2.14.0.3=h0d85af4_0
  - pandocfilters=1.4.2=py_1
  - panel=0.11.3=pyhd8ed1ab_0
  - param=1.11.1=pyh6c4a22f_0
  - parso=0.8.2=pyhd8ed1ab_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.3.1=py39ha4cf6ea_0
  - pip=21.1.3=py39hecd8cb5_0
  - pooch=1.4.0=pyhd8ed1ab_0
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.19=pyha770c72_0
  - protobuf=3.17.2=py39h9fcab8e_0
  - psutil=5.8.0=py39h89e85a6_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pygments=2.9.0=pyhd8ed1ab_0
  - pylint=2.9.3=py39hecd8cb5_1
  - pynndescent=0.5.4=pyh6c4a22f_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py39h89e85a6_2
  - pysocks=1.7.1=py39h6e9494a_3
  - python=3.9.5=h88f2d9e_3
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=1.9.0=py3.9_0
  - pytz=2021.1=pyhd3eb1b0_0
  - pyviz_comms=2.1.0=pyhd8ed1ab_0
  - pywavelets=1.1.1=py39hae3b40e_3
  - pyyaml=5.4.1=py39hcbf5805_0
  - pyzmq=22.1.0=py39h7fec2f1_0
  - readline=8.1=h9ed2024_0
  - requests=2.25.1=pyhd3deb0d_0
  - scikit-image=0.18.2=py39h4d6be9b_0
  - scikit-learn=0.24.2=py39h4b1dcc9_0
  - scipy=1.7.0=py39h056f1c0_0
  - send2trash=1.7.1=pyhd8ed1ab_0
  - setuptools=52.0.0=py39hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_0
  - snappy=1.1.8=hb1e8313_3
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sqlite=3.36.0=hce871da_0
  - tbb=2020.2=h940c156_4
  - tblib=1.7.0=pyhd8ed1ab_0
  - tensorboardx=2.4=pyhd8ed1ab_0
  - terminado=0.10.1=py39h6e9494a_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - threadpoolctl=2.2.0=pyh8a188c0_0
  - tifffile=2021.7.2=pyhd8ed1ab_0
  - tk=8.6.10=hb0a8c7a_0
  - toml=0.10.1=py_0
  - toolz=0.11.1=py_0
  - torchvision=0.2.2=py_3
  - tornado=6.1=py39h89e85a6_1
  - tqdm=4.61.2=pyhd3eb1b0_1
  - traitlets=5.0.5=py_0
  - typing_extensions=3.10.0.0=pyh06a4308_0
  - tzdata=2021a=h52ac0ba_0
  - umap-learn=0.5.1=py39h6e9494a_1
  - urllib3=1.26.6=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - wrapt=1.12.1=py39h9ed2024_1
  - xarray=0.18.2=pyhd8ed1ab_0
  - xz=5.2.5=h1de35cc_0
  - yaml=0.2.5=haf1e3a3_0
  - zeromq=4.3.4=h1c7c35f_0
  - zfp=0.5.5=he49afe7_5
  - zict=2.0.0=py_0
  - zipp=3.5.0=pyhd8ed1ab_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.9=h322a384_0
  - pip:
    - argparse==1.4.0
    - h5py==3.3.0
    - iniconfig==1.1.1
    - ipyparams==0.2.1
    - mofapy2==0.6.3
    - pluggy==0.13.1
    - py==1.10.0
    - pytest==6.2.4
    - rpy2==3.1.0
    - simplegeneric==0.8.1
    - tzlocal==2.1
prefix: /Users/bram/anaconda3/envs/vae
